"""add user email

Revision ID: c2f26703978f
Revises: ec805a7718eb
Create Date: 2024-08-08 22:13:18.120715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2f26703978f'
down_revision: Union[str, None] = 'ec805a7718eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'gym', ['id'])
    op.create_unique_constraint(None, 'reservation', ['id'])
    op.create_unique_constraint(None, 'review', ['id'])
    op.create_unique_constraint(None, 'service', ['id'])
    op.create_unique_constraint(None, 'trainer_schedule', ['id'])
    op.create_unique_constraint(None, 'trainer_services', ['id'])
    op.add_column('user', sa.Column('email', sa.String(length=150), nullable=True))
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'email')
    op.drop_constraint(None, 'trainer_services', type_='unique')
    op.drop_constraint(None, 'trainer_schedule', type_='unique')
    op.drop_constraint(None, 'service', type_='unique')
    op.drop_constraint(None, 'review', type_='unique')
    op.drop_constraint(None, 'reservation', type_='unique')
    op.drop_constraint(None, 'gym', type_='unique')
    # ### end Alembic commands ###
